### ISSUE TITLE
Problem with autofill password on log in

### ISSUE THREAD

**Issue by curlyz** [getblocky/codelab-esp#19]
When the username and password is autofill , this thing happen .
![ceb114d6-734f-4a10-af07-ee2c50eaefeb](https://user-images.githubusercontent.com/22770883/49628906-632fbf00-fa19-11e8-9b01-342335d088ec.jpeg)

User has to make some change to these field to make the log in button show up.
Critical UX . @phuc-it

**Comment by phucluke** [comment]
Cannot reproduce
